---
title: "Exploratory Analysis"
output: html_document
---

## Project title

Give your project a concise, interesting title that summarizes the entirety of your project

### Authors

Names of your team members

### Date

Winter 2022

### Abstract

No more than three sentences that summarize your project. Focus on the very most important aspects. For example: (1) "Our main question is .... This question is important because .... To address the question, we will ...." (2) "We are concerned with ..., because .... To address this concern, we plan to ...." (3) "Consider that .... This is important because .... Accordingly, we plan to ...."

### Keywords

3-5 keywords that summarize your project.
(e.g., "Keywords: human physiology; bicycle exercise; Gen Z; times-series data")

### Introduction  

Briefly introduce your project.  Include 3-5 research questions. What motivates the questions? Why are they important? (at least 200 words)

### Related Work  

Describe your topic and related work in this space. You must include 3 citations to related work (URLs to similar work, high quality articles from the popular press, research papers, etc. ) Please use a standard citation style of your choice. (at least 200 words)

### The Dataset

Where did you find the data? Please include a link to the data source  
Who collected the data?  
How was the data collected or generated?  
Why was the data collected?  
How many observations (rows) are in your data?  
How many features (columns) are in the data?  
What, if any, ethical questions or questions of power do you need to consider when working with this data?  
What are possible limitations or problems with this data?   (at least 200 words)

### Implications

Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

### Limitations & Challenges
What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1
Link to display chart:
file://Users/andrewyu/Dekstop/info%20prjct/chart1.html

code used to make chart:
install.packages("tidyverse)

{r setup, include=FALSE, , cache=TRUE}
knitr::otps_chunck$set(echo = FALSE)
library(tidyverse)
library(readr)

{r code}
data <- read_csv("test.csv")
ggplot(data, aes(x = race, fill = workclass)) + 
  geom_bar(position = "dodge")
  labs(x = "Race", y = "Count", fill = "Work Class", title = "Comparing Race and    Work Class")

This chart displays race compared to workclass. 
As shown, White individuals have the highest rate of employment in all of the included classes 
(federal gov, local gov, private, self-emp-inc, self-emp-not-inc, and state-gov). 
The most noticeable disparity is the difference between White people that are employed in private work classes compared to those of other races. 
White has the highest number, with a count over 500, whereas Black comes in second, with less than 100. 
This not only shows that race plays a role in employment, but that its impact seems to be significant. 
Level of employment directly translates to level of income, 
which is why analyzing how race plays a role in employment is important to tackling racial disparities regarding income. 

### Chart 2
setwd("~/Documents/archive")
data <- read.csv("test.csv")
ggplot(data, mapping = aes(x = education, y = occupation, color = gender)) +
  geom_point(position = "dodge") + 
  labs(x = "Education", y = "Occupation", fill = "Gender", title = "Comparing 
       education and occupation")
       

#{r, echo = FALSE, code = readLines("SecondChart.R")}

This chart displays education compared to occupation. 
As shown, higher education has the highest rate of employment compare to those
who dropped out early in shchool or didn't proceed higher education like college.
Using this graph we don't need to know what exactly the people hired in that specific occupation, but this graph is used for seeing the contrast between high education and low education. As it's shown in the lower education, there only 2 jobs that are willing to employ them, whereas the higher education have much more job opportunities and the quality of the job is also much higher compare to the lower education. 


### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
